version: '3'

services:

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mongodb'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongodb'
      - 'MONGO_INITDB_ROOT_USERNAME=mongodb'
    ports:
      - '27017'
    volumes:
      - mongo-data:/mongo
    networks:
      - mynetwork

  minio:
    image: minio/minio:latest
    container_name: minio-engself
    environment:
      - 'MINIO_BUCKET=images'
      - 'MINIO_URL=http://minio:9000'
      - 'MINIO_ACCESS_KEY=minioadmin'
      - 'MINIO_SECRET_KEY=minioadmin'
    command: server --address :9000 ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio
    networks:
      - mynetwork

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
      - mongodb
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/avatars;
      /usr/bin/mc mb myminio/checks;
      /usr/bin/mc policy set public myminio/avatars;
      /usr/bin/mc policy set public myminio/checks;
      exit 0;
      "
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  minio-data:
    driver: local
  mongo-data:
    driver: local
