version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
    command: mongod --noauth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://mongodb:27017/ --quiet
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 40s

  minio:
    image: minio/minio:latest
    container_name: minio-engself
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --address :9000 /data --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for Minio to be ready...';
        sleep 5;
      done;
      /usr/bin/mc mb myminio/avatars;
      /usr/bin/mc mb myminio/checks;
      /usr/bin/mc mb myminio/temp-checks;
      /usr/bin/mc policy set public myminio/avatars;
      /usr/bin/mc policy set public myminio/checks;
      /usr/bin/mc policy set public myminio/temp-checks;
      exit 0;
      "
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: 'zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - mynetwork
    healthcheck:
      test: echo stat | nc localhost 2181 | grep Mode
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - mynetwork
    healthcheck:
      test: |
        kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  mynetwork:
    driver: bridge

volumes:
  minio-data:
    driver: local
  mongo-data:
    driver: local