spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

---
# Конфигурация для локального окружения
spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
kafka:
  bootstrap-servers: localhost:9092
  topic:
    checkTopic: check-topic
  producer:
    acks: all
    retries: 3
    linger-ms: 1
minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  buckets:
    avatars: avatars
    checks: checks
    temp-checks: temp-checks
receipt:
  api:
    url: https://proverkacheka.com/api/v1/check/get
    token: 32540.G5winiT7cjsbp6Pa5
ml-service:
  url: http://158.160.109.57:5000
server:
  port: 8080

---
# Конфигурация для дев окружения
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: 158.160.109.57
      port: 27017
      database: mongodb
kafka:
  bootstrap-servers: 158.160.109.57:9094
  topic:
    checkTopic: check-topic
  producer:
    acks: all
    retries: 3
    linger-ms: 1
minio:
  url: http://158.160.109.57:9000
  accessKey: minioadmin
  secretKey: minioadmin
  buckets:
    avatars: avatars
    checks: checks
    temp-checks: temp-checks
receipt:
  api:
    url: https://proverkacheka.com/api/v1/check/get
    token: 32540.G5winiT7cjsbp6Pa5
ml-service:
  url: http://158.160.109.57:5000
server:
  port: 8080