spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
  kafka:
    bootstrap-servers: localhost:9092

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  buckets:
    avatars: avatars
    checks: checks
    temp-checks: temp-checks

receipt:
  api:
    url: https://proverkacheka.com/api/v1/check/get
    token: 32540.G5winiT7cjsbp6Pa5

server:
  port: 8080