spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb
      username: mongodb
      password: mongodb

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  buckets:
    avatars: avatars
    checks: checks

server:
  port: 8080