spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  buckets:
    avatars: avatars
    checks: checks

server:
  port: 8080